name: Deploy Resources

permissions:
 id-token: write
 contents: read

on:
  workflow_call:
    secrets:
      AWS_GITHUB_ACTIONS_ROLE:
        required: true
      AWS_TARGET_REGION:
        required: true

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout this repo
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
         role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
         aws-region: ${{ vars.AWS_TARGET_REGION }}
         role-session-name: "GitHubActions-DeployLayerStack"

     - name: Deploy LambdaStack (via CDK)
       uses: youyo/aws-cdk-github-actions@v2
       with:
         cdk_subcommand: 'deploy'
         cdk_args: '--require-approval never'
         actions_comment: false